### ISSUE TITLE
关于高级弹幕的几点说明

### ISSUE THREAD

**Issue by xubeiyan** [xubeiyan/kagariProject#1]
现在为止还没搞定高级弹幕的一种……
具体现象是只会显示第一条高级弹幕，而且是显示很多遍，明明用的代码和下方悬停弹幕一样……为什么呢，为什么会这样呢？第一次有了高级弹幕，第一次可以像字幕规定消失时间。两件快乐的事情重叠在一起……编不下去了（主要是怕被殴打吧）
而且type=2的弹幕好像也不能出现了……唔，我很慌啊~

**Comment by WindyDarian** [comment]
............................................................................................

**Comment by xubeiyan** [comment]
已经解决了……requestAnimationFrame这个函数的运行机制还是需要探究一下的……剧情大概是这样的：以前写的字幕出现的代码定死了stayTime = 3，然后发送时间检查是<0.1且>-0.1。就什么问题都没有……现在加了字幕stayTime是两位的小数了，于是发送时间检查内就会发n条出去，改成了<0.01且>-0.01就正常了……

**Comment by xubeiyan** [comment]
还是没搞懂这个的原理……总之那个问题又出现了……直接播放html5player2.html中的文件又会出现显示不出来的问题……但是有个办法，直接在时间轴上跳过最开始的那几个弹幕就行……我觉得是channelStatus2这个变量处理的问题……待我好好研究下……

**Comment by xubeiyan** [comment]
这个问题被解决了，将待加载弹幕排了个序，减少了addBarrageToPool那里的资源开销就正常了
